  version: 0.2
  os: linux
  files:
    - source: /springApp
      destination: /var/www/html
  hooks:
    BeforeInstall:
      - location: scripts/install_dependencies.sh
        timeout: 180
    AfterInstall:
      - location: scripts/start_server.sh
        timeout: 180
#version: 0.2
